# Generated by Django 5.0.1 on 2024-01-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('operator', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('data', models.TextField(null=True)),
                ('brcad', models.TextField()),
                ('topods_shape', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.CharField(max_length=50)),
                ('operation_history_ids', models.TextField()),
            ],
        ),
    ]
