# Generated by Django 5.0.1 on 2024-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('brcad', models.TextField()),
                ('topods_shape', models.TextField()),
            ],
        ),
    ]
