# Generated by Django 5.0.1 on 2024-01-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='topods_shape',
            field=models.BinaryField(),
        ),
    ]
