# Generated by Django 5.0.1 on 2024-01-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_alter_operation_topods_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='topods_shape',
            field=models.TextField(),
        ),
    ]
