# Generated by Django 5.0.1 on 2024-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0002_alter_operation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_time',
            field=models.IntegerField(),
        ),
    ]
