# Generated by Django 5.0.1 on 2024-02-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('operator_id', models.IntegerField()),
                ('time', models.IntegerField()),
                ('data', models.JSONField(null=True)),
                ('brcad', models.TextField()),
                ('topods_shape', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('create_time', models.IntegerField()),
                ('owner_id', models.IntegerField()),
                ('editor_ids', models.JSONField()),
                ('operation_history_ids', models.JSONField()),
            ],
        ),
    ]
