# Generated by Django 5.0.1 on 2024-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.TextField(default='{[1]}'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
