# Generated by Django 5.0.1 on 2024-03-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_alter_operation_brcad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('solid_id', models.TextField()),
                ('shape', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='topods_shape',
        ),
        migrations.AddField(
            model_name='operation',
            name='solid_ids',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
