# Generated by Django 5.0.1 on 2024-02-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0002_project_editors_alter_project_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
