# Generated by Django 5.0.1 on 2024-02-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0003_rename_owner_project_owner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operator',
        ),
        migrations.AddField(
            model_name='operation',
            name='operator_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
