# Generated by Django 5.0.1 on 2024-02-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cad', '0005_remove_project_editors_project_editor_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
